version: "3.8"

services:
  rsyncwebui:
    build:
      #context: https://github.com/Rubes78/RsyncWebUI.git
      context: /Quarks/Data/DevOps/RsyncWebUI
    container_name: rsyncwebui
    ports:
      - "5050:5050"
    environment:
      - FLASK_APP=rsync_web_browser.py
      - FLASK_ENV=production
      # Configuration for JSON file storage
      - CONFIG_PATH=/app/config
      - HISTORY_FILENAME=sync_history.json
      - PATHS_FILENAME=saved_paths.json
      - BROWSE_ROOT=/mnt/data
    volumes:
      - ${DOCKER_PATH}:/app/config
      - ${DATA_PATH}:/mnt/data/Quarks
      - ${USB_PATH}:/mnt/data/USB
    restart: unless-stopped
